FROM php:8.3-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git zip unzip curl libpng-dev libonig-dev libxml2-dev libzip-dev vim \
    && docker-php-ext-install pdo_mysql mbstring zip exif pcntl

# Sets working directory to /var/www and copies the projects structure
WORKDIR /var/www/html
COPY . .

# Gives permissions for directories
RUN chown -R www-data:www-data /var/www/html/storage \
    && chmod -R 775 /var/www/html/storage

# Executes php-fpm
CMD ["php-fpm"]
